export const CONFIG = {
  display: {
    storageKey: 'autoBladeDisplaySize',
    defaultSizeKey: '1080p',
    sizes: {
      '720p': { width: 1280, height: 720 },
      '1080p': { width: 1920, height: 1080 },
      '1440p': { width: 2560, height: 1440 },
      '4k': { width: 3840, height: 2160 }
    },
    gameWidth: 1920,
    gameHeight: 1080
  },

  theme: {
    font: {
      webFamily: 'Silkscreen',
      family: '"Silkscreen", monospace',
      loadTimeoutMs: 1200
    }
    ,
    textSize: {
      header                         : 20,
      body                           : 14,
      small                          : 14,

      inlineEmoji                    : 14,

      characterPanelLineHeight       : 20,

      formationSelectedUnitClass     : 14,
      formationTooltipTitle          : 20,
      formationTooltipBody           : 14,

      combatLogToggle                : 14,

      resourceRowLabel               : 14,
      resourceRowIcon                : 14,
      statsPopupResourceRowLabel     : 14,

      statsCpFlag                    : 14,
      setupUnitCardCostIcon          : 14,

      castTitle                      : 20,
      battleMainResource             : 14,
      battleLp                       : 14,
      damageNumber                   : 28,

      roundStartBannerTitle          : 28,
      roundStartBannerSubtitle       : 14,

      initiativeOrder                : 14,

      availableUnitName              : 20,
      availableUnitClass             : 14,
      availableUnitStats             : 14
    },
    colors: {
      background: '#050506',
      panel: '#111116',
      panelBorder: '#2e2e38',
      sky: '#0e3b58',
      grass: '#358f3d',
      formationGrid: '#a7a7a7',
      formationGridLine: '#4d4d4d',
      infoPanel: '#16161d',
      text: '#f5f5f5',
      mutedText: '#b9bbc8',
      redKnight: '#d84343',
      blueKnight: '#3f6fd9',
      spent: '#555862',
      sp: '#2e8fe8',
      hp: '#e04444',
      ap: '#d83535',
      rp: '#1a53a8',
      lp: '#f2cf45',
      emptyLp: '#5f5524',
      unitBorder: '#161616'
    },
    resourceIcons: {
      hp: '❤️',
      sp: '🛡️',
      ap: '🔶',
      rp: '🔷',
      lp: '⭐',
      ip: '🚩',
      mv: '🥾',
      rn: '⏹️'
    },
    resourceColors: {
      hp: '#e04444',
      sp: '#2e8fe8',
      ap: '#d83535',
      rp: '#1a53a8',
      lp: '#f2cf45',
      ip: '#5f5524'
    }
  },

  ui: {
    layout: {
      leftPanelWidthRatio: 0.29,
      centerWidthRatio: 0.42,
      rightPanelWidthRatio: 0.29,
      battleWindowHeightRatio: 0.48,
      unitSize: 140,
      infoPanelPadding: 6,
      infoColumnGap: 28,
      sideGridPadding: 40
    },
    utilityButton: {
      x: 24,
      yOffsetFromBottom: 104,
      width: 112,
      height: 30,
      gap: 8,
      padding: 12,
      depth: 220
    },
    speedMenu: {
      width: 72,
      optionHeight: 28,
      gap: 0,
      depthBonus: 10
    },
    utilityMenu: {
      buttonX: 8,
      buttonY: 8,
      buttonSize: 28,
      dropdownGapY: 6,
      dropdownWidth: 128,
      itemHeight: 32,
      gap: 4,
      label: '☰'
    },
    popup: {
      panelMargin: 24,
      panelTop: 64,
      sidePanelWidth: 420,
      sidePanelHeight: 560,
      logPanelWidth: 560,
      logPanelHeight: 480,
      statsPanelWidth: 350,
      statsPanelHeight: 820,
      panelPadding: 24,
      statsPanelPadding: 4,
      backgroundAlpha: 0.92,
      depth: 200,
      detailTextAlpha: 0.80
    },
    resourceRow: {
      labelTextPaddingY: 2,
      iconTextPaddingY: 4,
      labelWidth: 34,
      iconSpacing: 14,
      pairGap: 82,
      gap: 22,
      emptyAlpha: 0.10
    },
    statsCpRow: {
      flagSpacing: 18,
      iconXOffset: 34,
      flagTextPaddingY: 4
    },
    setupCardCostRow: {
      iconXOffset: 82
    },
    sideStatus: {
      showCards: false,
      gridTop: 82,
      cardWidth: 132,
      cardHeight: 136,
      gridColumnGap: 28,
      gridRowGap: 20
    },
    combatLog: {
      topOffset: 650,
      leftPadding: 28,
      toggleXOffset: 432,
      toggleYOffset: 0,
      toggleWidth: 48,
      toggleHeight: 28,
      togglePadding: 8,
      toggleVisibleLabel: 'X',
      toggleHiddenLabel: 'LOG',
      maxLines: 16,
      lineHeight: 20
    },
    depths: {
      background: 0,
      grid: 10,
      shadow: 20,
      unit: 30,
      unitHud: 40,
      damageText: 80,
      combatCallout: 100,
      battleResourceCenterBonus: 30,
      setupUi: 150
    },
    formationMenu: {
      buttonX: 24,
      buttonY: 42,
      buttonSize: 34,
      panelWidth: 150,
      panelHeight: 204,
      titleYOffset: 16,
      optionHeight: 32,
      optionGap: 6,
      optionXOffset: 12,
      optionYOffset: 44,
      selectedMark: '•'
    },
    tooltip: {
      formationBodyYOffset: 62,
      defaultTitle: 'Info',
      defaultText: 'Hover a stat icon for details.'
    }
  },

  formation: {
    rows: ['front', 'middle', 'back'],
    cols: [0, 1, 2],
    rowOrderRed: ['back', 'middle', 'front'],
    rowOrderBlue: ['front', 'middle', 'back'],
    setup: {
      minUnitsToStart: 1,
      aiDefaultCommandSpend: 6,
      panelX: 480,
      panelY: 124,
      panelWidth: 1380,
      panelHeight: 470,
      panelAlpha: 0.88,
      buttonHeight: 34,
      knightCardWidth: 190,
      knightCardHeight: 154,
      startButtonWidth: 150,
      commandIcon: '💲',
      titleYOffset: 18,
      unitTypes: ['squire', 'thief', 'knight', 'archer'],
      unitCardGap: 14,
      unitsTitleXOffset: 18,
      unitsCardXOffset: 18,
      unitsCardYOffset: 90,
      promotedUnitsCardYOffset: 272,
      knightCardTitleXOffset: 14,
      knightCardTitleYOffset: 10,
      knightCardCostYOffset: 42,
      knightPreviewXOffset: 14,
      knightPreviewYOffset: 66,
      knightPreviewLabelWidth: 32,
      knightPreviewRowGap: 14,
      cellAlphaPlayer: 0.18,
      cellAlphaAi: 0.08,
      cpTooltipOffsetX: 18,
      cpTooltipOffsetY: 18,
      cpTooltipPadding: 8,
      cpTooltipWidth: 150,
      cpTooltipHeight: 70,
      cellAlphaOccupied: 0.28,
      cellStrokePlayer: '#58a6ff',
      cellStrokeAi: '#5f6674',
      previewAlphaPlayer: 1,
      previewAlphaAi: 0.72
    },
    squads: {
      maxSquads: 6,
      availableUnitsColumns: 6,
      availableUnitsVisibleRows: 2,
      doubleClickMs: 280,
      unitDragThreshold: 8,
      commandIcon: '👑',
      selectedSquadHighlight: '#58a6ff',
      selectedUnitHighlight: '#f2cf45',
      columnGap: 16,
      sectionPadding: 16,
      scrollbarWidth: 12,
      leftStatsPanelX: 24,
      leftStatsPanelHeight: 655,
      leftPanelGap: 14,
      headerY: 42,
      commandLevelBoxWidth: 430,
      commandLevelBoxHeight: 54,
      commandLevelControlSize: 24,
      commandLevelControlGap: 14,
      viewportXOffset: 16,
      sectionPaddingTop: 55,
      sectionPaddingBottom: 28,
      visibleCardsPerPage: 3,
      visibleColumns: 3,
      visibleRows: 1,
      totalRows: 2,
      cardWidth: 432,
      cardHeight: 340,
      cardHeaderHeight: 64,
      cardBodyBottomPadding: 16,
      cardGap: 20,
      boardXOffset: 88,
      boardCellSize: 80,
      boardCellGap: 8,
      boardCols: 3,
      boardRows: 3,
      boardEmptyAlpha: 0.58,
      boardOccupiedAlpha: 0.96,
      boardOccupiedColor: '#20202a',
      cellUnitArtScale: 3.1,
      cellUnitArtOffsetY: -12,
      cellNameOffsetY: -7,
      cellNameOffsetX: -2,
      cellNameBackingAlpha: 0.72,
      dragGhostAlpha: 0.86,
      dragGhostNameOffsetY: -28,
      dragGhostSpriteOffsetY: 0,
      selectedCellHighlight: '#f2cf45',
      backgroundColor: 0x2f3434,
      assignedCardAlpha: 0.48,
      assignedCardFillColor: '#2b2d31'
    },
    roster: {
      pickerBottomAnchorY: 1012,
      availableUnitsCellGap: 14,
      availableUnitsScrollSpeed: 1,
      cardWidth: 209,
      cardHeight: 209,
      panelHeaderHeight: 42,
      panelExtraWidth: 12,
      unitArtScale: 5.5,
      unitArtCenterYOffset: 74,
      unitStatsYOffset: 126,
      unitStatsRowGap: 18,
      unitStatsGroupReservedWidth: 52,
      unitStatsGroupGap: 20,
      unitStatsIconSpacing: 13
    }
  },

  battle: {
    defaultSpeedMultiplier: 2,
    speedOptions: [1, 2, 4, 8, 16, 32, 64],
    knight: {
      randomIdleTwitchEnabled: false,
      randomIdleTwitchTestKey: 'I',
      randomIdleTwitchDelayMs: 15000,
      randomIdleTwitchHoldMs: 1000,
      attackActionKeys: ['slash', 'thrust', 'shiv'],
      blockSyncLeadFrames: 1,
      showUnitNameLabels: false
    },
    battlefield: {
      horizonRatio: 0.50,
      skyStarCount: 42,
      skyStarColor: '#f5f5f5',
      skyStarAlpha: 0.36,
      skyStarMinSize: 1,
      skyStarMaxSize: 2,
      skyStarTopPadding: 18,
      skyStarBottomPadding: 22,
      formationGridLineColor: '#23652d',
      formationGridLineSize: 2,
      formationCenterYRatio: 0.75,
      formationCenterYOffset: -2,
      formationColumnSpacing: 166.67,
      formationRowSpacing: 170,
      showGridLines: false,
      gridToggleKey: 'G',
      gridLineAlphaVisible: 0.45,
      gridLineAlphaHidden: 0,
      unitVisualYOffset: 0,
      unitSpriteForwardXOffset: 24,
      teamUnitTintEnabled: true,
      redTeamUnitTint: '#d84343',
      blueTeamUnitTint: '#3f6fd9',
      unitShadowColor: '#071309',
      unitShadowAlpha: 0.38,
      unitShadowWidth: 80,
      unitShadowHeight: 8,
      unitShadowYOffset: 64
    },
    castCallout: {
      yOffset: 0,
      width: 160,
      height: 35,
      padding: 6,
      borderColor: '#ffffff',
      backgroundColor: '#050506'
    },
    hud: {
      showUnitHud: true,
      mainResourceStaticSlots: true,
      mainResourceRowYOffset: 78,
      mainResourceIconSpacing: 8,
      mainResourceGroupGap: 0,
      mainResourceMajorGap: 18,
      mainResourceEmptyAlpha: 0.16,
      mainResourceStaticMaxSlots: 4,
      mainResourceStaticIconSpacing: 10,
      mainResourceStaticGroupGap: 20,
      mainResourceStaticRowGap: 14,
      battleStateFullAlpha: 1,
      backplateEnabled: true,
      backplateWidth: 100,
      backplateHeight: 30,
      backplateYOffset: 85,
      backplateColor: '#050506',
      backplateAlpha: 0.10,
      backplateBorderColor: '#2e2e38',
      backplateBorderThickness: 0,
      lpShow: true,
      lpXOffset: 30,
      lpYOffset: 54,
      lpCornerXInset: 8,
      lpCornerYInset: 8
    },
    damage: {
      popupYOffset: 80,
      numberXOffset: 0,
      numberYOffset: 60,
      numberDurationMs: 1000,
      numberFloatY: 20,
      numberHoldMs: 1000,
      blinkAlpha: 0.4,
      blinkDurationMs: 160,
      blinkRepeat: 1
    },
    roundBanner: {
      enabled: true,
      width: 560,
      height: 150,
      yRatio: 0.26,
      holdMs: 3600,
      actionStartDelayMs: 500,
      fadeMs: 500,
      depth: 180,
      backgroundAlpha: 0.78,
      backgroundColor: '#071b35',
      borderColor: '#58a6ff',
      titleColor: '#d8ecff',
      subtitleColor: '#9dccff'
    },
    fatigue: {
      startRound: 5,
      intervalRounds: 5,
      rpRecoveryPenalty: 1
    },
    exhaustion: {
      startRound: 10,
      intervalRounds: 5,
      rpDrain: 1
    },
    initiativeOrder: {
      showNumber: true,
      centerXOffset: 5,
      yOffset: 65,
      color: '#ffffff',
      strokeThickness: 4,
      activeAlpha: 1,
      actedAlpha: 0.20,
      ineligibleAlpha: 0.10
    },
    timing: {
      battleOverBannerHoldMs: 1400,
      attackResourcePreviewMs: 650,
      attackResourceCommitMs: 200,
      postAttackResourcePauseMs: 150,
      defenderLpGainStaggerMs: 250,
      lungeMs: 450,
      freezeMs: 300,
      returnMs: 450,
      moveAnimationMs: 450,
      moveAnimationEase: 'Sine.easeInOut',
      attackLungeStopDistance: 132,
      attackerCounterResourceMs: 450,
      finalStatsMs: 750,
      cleanupBufferMs: 300,
      floatingEffectMs: 300,
      counterResourcePreviewMs: 500,
      secondaryResourceCommitStaggerMs: 250,
      dodgeFlipMs: 300,
      dodgeFlipBackDistance: 28,
      dodgeFlipUpDistance: 22,
      dodgeFlipRotationDegrees: 360,
      dodgeFlipFadeAlpha: 0.55,
      dodgeFlipReturnMs: 120,
      dodgeFailTiltDegrees: 90,
      dodgeFailDropDistance: 16,
      dodgeFailMs: 260,
      dodgeFailRecoverMs: 220,
      dodgeFailBlinkAlpha: 0.45,
      dodgeFailBlinkCount: 2,
      dodgeRpRefundVisualDelayMs: 200,
      rangedProjectileMs: 450,
      rangedProjectileArcHeight: 80,
      rangedProjectileSize: 5,
      rangedProjectileStartXOffset: 12,
      rangedProjectileStartYOffset: -40,
      rangedProjectileEndXOffset: 0,
      rangedProjectileEndYOffset: -35,
      koFadeAlpha: 0.10,
      koRemoveDelayMs: 500,
      actionCastResourceDelayOffsetMs: 90,
      noReactionImpactPauseMs: 200,
      combatZoomKey: 'F',
      combatZoomPadding: 0,
      combatZoomMs: 250,
      resourceEffectCommitDelayMs: 400,
      castEffectFadeOffsetMs: 600
    }
  },

  command: {
    levelMin: 1,
    levelMax: 9,
    levelDefault: 2,
    startingLevel: 2,
    startingXp: 0,
    xpToLevel: 10,
    startingEnemyLevel: 6,
    startingEnemyXp: 0
  },

  practice: {
    enemyCount: 2,
    enemyAllowedClasses: ['squire', 'thief', 'archer'],
    enemyFormationSlots: [
      { row: 'front', col: 1 },
      { row: 'back', col: 1 }
    ],
    demoAvailableUnitClasses: [
      'squire', 'squire', 'squire', 'squire',
      'thief', 'thief', 'thief', 'thief',
      'archer', 'archer', 'archer', 'archer',
      'knight', 'knight', 'knight', 'knight', 'knight', 'knight'
    ],
    armyRosterNamePool: [
      'Alden', 'Bria', 'Cedric', 'Dara', 'Emery', 'Faye',
      'Garrick', 'Hale', 'Iris', 'Jory', 'Kael', 'Lena',
      'Mira', 'Nolan', 'Orin', 'Petra', 'Quinn', 'Rhea',
      'Silas', 'Tessa', 'Ulric', 'Vera', 'Wren', 'Yara'
    ]
  }
};
